# Genel Ayarlar (Tüm Profiller İçin Ortak)
spring:
  application:
    name: denizbank-service
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: buysell
  datasource:
    username: admin
    password: 1234

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # Varsayılan değer
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Localhost Profili
---
spring:
  config:
    activate:
      on-profile: localhost
  datasource:
    url: jdbc:postgresql://localhost:5433/buysell

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

server:
  port: 9788

# Docker Profili
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/buysell

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8080
