# Genel Ayarlar

spring:
  application:
    name: eureka-server

eureka:
  instance:
    appname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

# Localhost Profili
---
spring:
  config:
    activate:
      on-profile: localhost

info:
  component: Eureka Server - Prod Configs - Localhost

eureka:
  instance:
    hostname: localhost

server:
  port: 8763

# Stage Profili
---
spring:
  config:
    activate:
      on-profile: stage

info:
  component: Eureka Server - Prod Configs - Stage

eureka:
  instance:
    hostname: eureka-server-stage

server:
  port: 8765
  renewal-percent-threshold: 0.85
